---
title: "DataFest2021"
author: "Elias Lai, Jordan McGilvery, Jason Gerber, Jason Shang"
date: "04/09/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      comment = "#>", highlight = TRUE, error = TRUE,
                      fig.align = "center")
```

## Packages

```{r packages}
library(tidyverse)
library(broom)
```

```{r read ca.csv}
canada <- read.csv("data/ca.csv")
```

#### Adding columns based on drugs
#whether or not this person uses perscription drugs (1 = yes, 0 = no)
```{r mutate_drug_use_yesorno}
canada <- canada %>% 
  mutate(druguse_yn = ifelse(FENT_USE+BUP_USE+MORPH_USE+OXY_USE+OXYM_USE+
                             TRAM_USE+TAP_USE+COD_USE+HYD_USE+HYDM_USE+SUF_USE 
                             > 0, 1, 0))
```
#number of drugs the person uses 
```{r mutate_drug_use_number}
canada <- canada %>% 
  mutate(druguse_num = FENT_USE+BUP_USE+MORPH_USE+OXY_USE+OXYM_USE+TRAM_USE+
                      TAP_USE+COD_USE+HYD_USE+HYDM_USE+SUF_USE)
```
#whether or not person has abused any drugs (yes = 1, no = 0)

```{r mutate_drug_nopres_yesorno}
canada <- canada %>% 
  mutate(drugnopres_yn = ifelse(rowSums(canada[,c("FENT_NMU","BUP_NMU","MORPH_NMU","OXY_NMU","OXYM_NMU","TRAM_NMU","TAP_NMU","COD_NMU","HYD_NMU","HYDM_NMU","SUF_NMU")], na.rm = TRUE)> 0, 1, 0))
```
#counts the number of drugs that each person abuses and creates a new column
```{r mutate_drug_nopres_number}
canada$drugnopres_num = rowSums(canada[,c("FENT_NMU","BUP_NMU","MORPH_NMU","OXY_NMU","OXYM_NMU","TRAM_NMU","TAP_NMU","COD_NMU","HYD_NMU","HYDM_NMU","SUF_NMU")], na.rm = TRUE)
```

```{column for has mental disorder}
#Ment_None
```

```{r mutate num_mental_disorders}
#column lists number of mental disorders that the user has 
canada <- canada %>% 
  mutate(num_mental_disorders = rowSums(canada[,c("MENT_ANX","MENT_ADHD","MENT_AUT","MENT_BIP","MENT_BPD","MENT_DEP","MENT_EAT","MENT_OCD","MENT_PANIC","MENT_PPD","MENT_PTSD", "MENT_SCH", "MENT_OTH")], na.rm = TRUE))
```

```{r mutate num_traumatic_disorders}
#column lists number of traumatic mental disorders that the user has 
canada <- canada %>% 
  mutate(num_traumatic_disorders = rowSums(canada[,c("MENT_ANX","MENT_DEP","MENT_PANIC","MENT_PPD","MENT_PTSD", "MENT_SCH")], na.rm = TRUE))
```

```{r plot_numtraumaticdisorders_vs_drugnopres_num}
ggplot(data = canada, 
       mapping = aes(x = num_mental_disorders, y = drugnopres_num)) + 
   geom_point() + 
   geom_smooth()
```


## References

- Computing for the Social Sciences. "Logistic Regression." 
  https://cfss.uchicago.edu/notes/logistic-regression/